balance:
  less:
    anchor_set: 500000
    num_keys: 500000
    num_removals: 10000
    working_set: 500000
  more:
    anchor_set: 1000000
    num_keys: 1000000
    num_removals: 20000
    working_set: 1000000
    