common:
    output-folder: /tmp
    iterations:
        warmup: 5
        run: 10
    init-nodes: [10, 100, 1000, 10000, 100000]
    hash-functions:
        - crc32
        - md5
        - murmur3
        - xx

algorithms:
    - name: anchor
    - name: dx
    - name: jump
    - name: maglev
    - name: memento
    - name: multi-probe
    - name: power
    - name: rendezvous
    - name: ring

benchmarks:
    - name: balance
    - name: init-time
    - name: lookup-time
      args:
          distributions:
              - uniform
              - normal
              - custom
    - name: memory-usage
    - name: monotonicity
      args:
          fractions: [0.1, 0.3, 0.5]
    - name: resize-balance
    - name: resize-time
