algorithms:
    - name: anchor
    - name: dx
    - name: jump
    - name: maglev
    - name: memento
    - name: multi-probe
    - name: power
    - name: rendezvous
    - name: ring
benchmarks:
    - name: balance
    - name: init-time
    - name: lookup-time
      args:
          distributions:
              - uniform
    - name: memory-usage
    - name: monotonicity
      args:
          fractions:
              - 0.1
    - name: resize-balance
    - name: resize-time
common:
    hash-functions:
        - xx
    init-nodes:
        - 10
    iterations:
        run: 1
        warmup: 1
    output-folder: tmp/
    time:
        run: 1
        warmup: 1