algorithms:
    - name: anchor
      args:
          capacity: 10
    - name: dx
      args:
          capacity: 10
    - name: jump
    - name: maglev
      args:
          permutations: 128
    - name: memento
    - name: multi-probe
      args:
          probes: 21
    - name: power
    - name: rendezvous
    - name: ring
      args:
          virtualNodes: 1000
benchmarks:
    - name: balance
      common:
          args:
              key-multiplier: 100
    - name: init-time
    - name: lookup-time
      args:
          removal-order: lifo
          removal-rate: 0
    - name: memory-usage
    - name: monotonicity
      common:
          args:
              fractions:
                  - 0.1
                  - 0.3
                  - 0.5
              keyMultiplier: 100
    - name: resize-balance
      common:
          args:
              key-multiplier: 100
    - name: resize-time
common:
    gc: true
    hash-functions:
        - crc32
        - md5
        - murmur3
        - xx
    init-nodes:
        - 10
        - 100
        - 1000
        - 10000
    iterations:
        run: 5
        warmup: 5
    key-distributions:
        - uniform
        - normal
        - custom
    output-folder: tmp/
    time:
        execution: 5
        mode: AverageTime
        run: 1
        unit: NANOSECONDS
        warmup: 5